version: '3'

services:
  db:
    image: postgres:16
    container_name: volcana-db
    environment:
      POSTGRES_USER: volcana
      POSTGRES_PASSWORD: volcana
      POSTGRES_DB: volcana
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - volcana-net

  backend:
    build:
      context: ../backend
    container_name: volcana-backend
    env_file:
      - ../backend/.env
    depends_on:
      - db
    networks:
      - volcana-net
    volumes:
      - media_data:/app/media


  frontend:
    build:
      context: ../frontend
    container_name: volcana-frontend
    depends_on:
      - backend
    networks:
      - volcana-net


  nginx:
    image: nginx:alpine
    container_name: volcana-core-nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8002:80"    
    networks:
      - volcana-net

volumes:
  db_data:
  media_data:

networks:
  volcana-net:
    driver: bridge
